server:
  httpPort: "8877"
db:
  connectToDB: "host=147.45.165.193 port=5432 user=currency_p1n41k password=qwerty1 dbname=currency_db sslmode=disable"

jwt:
  secret: "auth-secret-key"

logging:
  level: "info"
  development: true
