server:
  httpPort: ":8877"
  
db:
  connectToDB: "host=147.45.165.193 port=5432 user=currency_p1n41k password=qwerty1 dbname=postgres sslmode=disable"
  migrationsPath: "../../migrations"

jwt:
  secret: "secret-key"

logging:
  level: "info"
  development: true
